PresentationLayer/Controllers/AddArtworkController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DataLayer.Data;
using System.Text.Encodings.Web;
using DataLayer.Models;
using PresentationLayer.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using DataLayer.Models.Auth;

using DataLayer.UnitOfWork;
namespace museum_management.Controllers{
    
    [Authorize (Roles = UserRoles.CatalogManager)]
    public class AddArtworkController : Controller
    {
        private readonly IUnitOfWork _uniOfWork;

        public AddArtworkController (IUnitOfWork unitOfWork){
            _uniOfWork = unitOfWork;
        }
        [HttpGet]
        public IActionResult Index(){
    
            return View();
        }
        [HttpPost, ActionName("Index")]
        public IActionResult AddArtwork([Bind("Title,Author,EconomicValue,Period,CreationDate,MuseumRoom")] AddArtworkViewModel addArtworkViewModel){
            if(ModelState.IsValid){
                Artwork artwork = new Artwork();
                artwork.Title = addArtworkViewModel.Title;
                artwork.Author = addArtworkViewModel.Author;
                artwork.EconomicValue = addArtworkViewModel.EconomicValue;
                artwork.Period = addArtworkViewModel.Period;
                artwork.CreationDate = addArtworkViewModel.CreationDate;
                artwork.EntryDate = DateTime.Now.Date;
                artwork.MuseumRoom = addArtworkViewModel.MuseumRoom;
                artwork.LendingToMuseums = new List<LendingToMuseum>();
                artwork.Restaurations = new List<Restauration>();
                artwork.ActualMuseumId = 3;
                artwork.OriginMuseumId = 3;
                
                System.Console.WriteLine("datetime");
                System.Console.WriteLine(artwork.EntryDate);
                _uniOfWork.Artworks.Add(artwork);
                _uniOfWork.Complete();
                return RedirectToAction("Index", "Catalog");
            }
            var errors = ModelState.Select(x => x.Value.Errors)
                           .Where(y=>y.Count>0)
                           .ToList();

            foreach(var error in errors){
                foreach(var e in error){
                    System.Console.WriteLine(e.ErrorMessage);
                }
            }
            return View(addArtworkViewModel);
        }
        
       

}
}

PresentationLayer/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DataLayer.Data;
using System.Text.Encodings.Web;
using DataLayer.Models;
using PresentationLayer.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using DataLayer.Models.Auth;
using DataLayer;
using DataLayer.UnitOfWork;


namespace museum_management.Controllers{
    [AllowAnonymous]
    public class CatalogController : Controller {
        
        private readonly IUnitOfWork _unitOfWork;

        public CatalogController(IUnitOfWork unitOfWork) {
            _unitOfWork = unitOfWork;
        }
    
        // public IActionResult Restaurations(int id , int artworkid) {
          

        //     var restaurations = _unitOfWork.Restaurations.GetById(id, artworkid);
        //     // Where(r => r.ArtworkId == id).ToListAsync();

        //     if (restaurations == null) {
        //         return NotFound();
        //     }
            
        //     return View(restaurations);
            

        // }

       

        public IActionResult Edit(int id){
        

            var artwork = _unitOfWork.Artworks.GetById(id);
            // FirstOrDefaultAsync(m => m.Id == id);

            if (artwork == null) {
                return NotFound();
            }

            return View(artwork);
        }

        public IActionResult Delete(int id){
        
            var artwork = _unitOfWork.Artworks.GetById(id);
                // .FirstOrDefaultAsync(m => m.Id == id);
            if (artwork == null) {
                return NotFound();
            }

            return View(artwork);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id){
            var artwork = _unitOfWork.Artworks.GetById(id);
            _unitOfWork.Artworks.Remove(artwork);
            _unitOfWork.Complete();
            return RedirectToAction(nameof(Index));
        }
        
        public  IActionResult Index(string artworkroom)
        {
            var artworks = _unitOfWork.Artworks.GetArtworksByMuseumId(3).ToList();
            
            if (!string.IsNullOrEmpty(artworkroom))
            {
                artworks = artworks.Where(x=> x.MuseumRoom == artworkroom).ToList();
            }
            var lastResaturation = new List<Restauration>();
            var restaurations = _unitOfWork.Restaurations.GetAll().ToList();
            
            
            foreach(var art in artworks)
            {
                var restaurationActual = new List<Restauration>();
                foreach(var rest in restaurations)
                {
                    if (art.Id == rest.ArtworkId) restaurationActual.Add(rest);
                }

                if(restaurationActual.Count == 0) 
                {
                    lastResaturation.Add(new Restauration {
                        ArtworkId = art.Id,
                        Artwork = art,
                        StartDate = DateTime.Now
                    });
                }
                else
                lastResaturation.Add(restaurationActual[restaurationActual.Count-1]);

            }
            foreach(var x in artworks){
                System.Console.WriteLine(x.Restaurations == null);
            }
            // artworks = artworks.Where(x=>x.Restaurations.Count==0 || DateTime.Now > x.Restaurations[x.Restaurations.Count-1].EndDate).ToList();
            var artworkRoomVM = new ArtworkRoomViewModel
            {
                MuseumRoom = new SelectList( _unitOfWork.Artworks.GetArtworksByMuseumId(3).Select(m => m.MuseumRoom).Distinct()),
                Artworks = artworks,
                LastResaturation = lastResaturation
            };

            return View(artworkRoomVM);
        }
    }
}

PresentationLayer/Controllers/LendingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DataLayer.Data;
using PresentationLayer.ViewModels;
using DataLayer.Models.Auth;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using DataLayer;
using DataLayer.UnitOfWork;
using DataLayer.Models;

namespace museum_management.Controllers{
    [Authorize(Roles = UserRoles.Director)]
    public class LendingController: Controller{
            
            private readonly IUnitOfWork _unitOfWork;
    
            public LendingController( IUnitOfWork unitOfWork) {
                _unitOfWork = unitOfWork;
            }
    
            public IActionResult Index(string? currentLendingState) {
                System.Console.WriteLine("SearchState");
                System.Console.WriteLine(currentLendingState);
                IEnumerable<LendingToMuseum> lendingToMuseums;
                List<LendingViewModel> lendingViewModels = new List<LendingViewModel>();

                if(currentLendingState != null) {
                    lendingToMuseums = _unitOfWork.Lendings.GetLendingsByState(currentLendingState);
                }
                else{
                    lendingToMuseums = _unitOfWork.Lendings.GetAll();
                }
                foreach (var lending in lendingToMuseums) {
                    var artwork = _unitOfWork.Artworks.GetById(lending.ArtworkId);
                    var museum = _unitOfWork.Museums.GetById(lending.MuseumId);
                    lendingViewModels.Add(new LendingViewModel {
                        
                        ArtworkId = lending.ArtworkId,
                        MuseumId = lending.MuseumId,
                        LendingToMuseum = lending,
                        ArtworkTitle = artwork.Title,
                        MuseumName = museum.Name,
                        
                        
                    });
                }
                    // Create LendingTableViewModel
                LendingTableViewModel lendingTableViewModel = new LendingTableViewModel
                {
                    CurrentLendingState=currentLendingState==null ? "" : currentLendingState,
                    LendingStateList = new SelectList(_unitOfWork.Lendings.GetAll().Select(m => m.LendingState).Distinct()),
                    LendingViewModels = lendingViewModels
                    
                };
                   
                // System.Console.WriteLine(  "mmmm");
                // System.Console.WriteLine("LendingToMuseums: " + lendingToMuseums[0].ArtworkId);
                return View(lendingTableViewModel);
            }


            public IActionResult Edit(int artworkId, int museumId){
                var lending = _unitOfWork.Lendings.GetById(artworkId,museumId);
                var artwork = _unitOfWork.Artworks.GetById(artworkId);
                var museum = _unitOfWork.Museums.GetById(museumId);
                var artworklendingViewModel = new ArtworklendingViewModel();
                artworklendingViewModel.ArtworkId = lending.ArtworkId;
                artworklendingViewModel.MuseumId = lending.MuseumId;
                artworklendingViewModel.Author = artwork.Author;
                artworklendingViewModel.ArtworkTitle = artwork.Title;
                // {
                
                //     Id = lending.Id,
                //     ArtworkTitle = artwork.Title,
                //     Author = artwork.Author,
                   
                // };
                return View(artworklendingViewModel);
            }
            
            
            public IActionResult Accept(int artworkId, int museumId){
                var lending = _unitOfWork.Lendings.GetById(artworkId,museumId);
                lending.LendingState = LendingState.Lended;
                // _unitOfWork.Lendings.Update(lending);
                _unitOfWork.Complete();
                return RedirectToAction("Index");
            }

            
            public IActionResult Reject(int artworkId, int museumId){
                var lending = _unitOfWork.Lendings.GetById(artworkId,museumId);
                lending.LendingState = LendingState.Denied;
                _unitOfWork.Complete();
                return RedirectToAction("Index");
                

            }
    
    }

}

PresentationLayer/Controllers/RestaurationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DataLayer.Data;
using PresentationLayer.ViewModels;
using DataLayer.Models.Auth;
using Microsoft.AspNetCore.Authorization;
using DataLayer.UnitOfWork;
using DataLayer.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace museum_management.Controllers{
    [Authorize (Roles = UserRoles.Restaurator)]
    public class RestaurationController: Controller{
            
            private readonly IUnitOfWork _unitOfWork;
    
            public RestaurationController(IUnitOfWork unitOfWork) {
                _unitOfWork = unitOfWork;
            }
    
            public IActionResult Index() {
                var restaurations =  _unitOfWork.Restaurations.GetAll().ToList();
                List<RestaurationViewModel> restaurationViewModels = new List<RestaurationViewModel>();
                foreach(var restauration in restaurations){
                    var artwork =  _unitOfWork.Artworks.GetById(restauration.ArtworkId);
                    restaurationViewModels.Add(new RestaurationViewModel{
                        ArtworkTitle = restauration.Artwork.Title,
                        Restauration = restauration
                    });
                }

                return View(restaurationViewModels);
            }


            public IActionResult Add(int artworkId){
                CreateRestaurationViewModel createRestaurationViewModel = new CreateRestaurationViewModel();
                createRestaurationViewModel.ArtworkId = artworkId;
                createRestaurationViewModel.TypeRestauration="";
                
                return View(createRestaurationViewModel);
            }
            
            [HttpPost, ActionName("Add")]
            public IActionResult AddARestauration(int artworkId, [Bind("TypeRestauration")] CreateRestaurationViewModel createRestaurationViewModel){
                if(ModelState.IsValid){
                    Restauration restauration = new Restauration();
                    restauration.ArtworkId = artworkId;
                    System.Console.WriteLine(artworkId);
                    System.Console.WriteLine("MMMM");

                    restauration.StartDate = DateTime.Now.Date;
                    System.TimeSpan duration = new System.TimeSpan(90, 0, 0, 0); 
                    restauration.EndDate = (DateTime.Now).Add(duration);
                    restauration.RestaurationType = createRestaurationViewModel.TypeRestauration;
                    restauration.Artwork = _unitOfWork.Artworks.GetById(artworkId);
                    _unitOfWork.Restaurations.Add(restauration);
                    _unitOfWork.Complete();
                    return RedirectToAction("Index");
                }
                var errors = ModelState.Select(x => x.Value.Errors)
                            .Where(y=>y.Count>0)
                            .ToList();

                foreach(var error in errors){
                    foreach(var e in error){
                        System.Console.WriteLine(e.ErrorMessage);
                    }
                }
                return RedirectToAction("Add", artworkId);
            }
            
            // public IActionResult Restauration()
            // {
            //     CreateRestaurationViewModel createRestaurationViewModel = new CreateRestaurationViewModel();
            //     var restaurationTypes = new List<string>();
            //     restaurationTypes.Add(RestaurationType.Complete.ToString());
            //     restaurationTypes.Add(RestaurationType.Minimal.ToString());
            //     restaurationTypes.Add(RestaurationType.Partial.ToString());
            //     createRestaurationViewModel.TypeRestauration = new SelectList(restaurationTypes);
            //     return View(createRestaurationViewModel);
            // }
    }
}

PresentationLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Catalog Museum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/museum_management.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Catalog" asp-action="Index"> Catalog Museum</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if ( User.IsInRole("Restaurador"))
                {
                    <a class="nav-link text-dark" asp-area="" asp-controller="Restauration" asp-action = "Index">Restauration</a>
                }
               @if ( User.IsInRole("Director"))
               { 
                  <a class="nav-link text-dark" asp-area="" asp-controller="Lending" asp-action = "Index">Lending</a>
                  <a class="nav-link text-dark" asp-area="" asp-controller="BorrowArtworks" asp-action = "Index">Borrow</a>
               }
                    
               @if ( User.IsInRole("Admin"))
               { 
                  
                  <a class ="nav-link text-dark" asp-area="" asp-controller="User" asp-action = "Index">User Management</a>
               }
               @if(User.IsInRole("Encargado del Catalogo")) 
                { 
                   <a class ="nav-link text-dark" asp-area="" asp-controller="AddArtwork" asp-action = "Index">Add Artwork</a>
                } 
                    
                <div class="navbar-collapse d-flex flex-row-reverse">
                    <ul class="navbar-nav">
                        @if (User.IsInRole("Admin"))
                        {
                            
                            <a class="nav-link text-dark pull-right  active" asp-area="Identity" asp-page="/Account/Register">Register</a>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                     @User.Identity.Name 
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout">Logout</a>
                                </div>
                            </li>
                        }
                        else if (!@Context.Request.Path.Value.Contains("Authentication")){
                            <li class="nav-item">
                                <a class="nav-link text-dark pull-right  active" asp-area="Identity" asp-page="/Account/Login" >Log In</a>
                            </li>
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container body-content">
        @RenderBody()
    </div>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Catalog Museum - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>